<?php
/**
 * IPC2017 Zend\Expressive Workshop
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/RalfEggert/ipc2017-expressive
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('Home'); ?>

<div class="jumbotron">
  <h1>Herzlich Willkommen!</h1>
  <p>
    Im Workshop &quot;Zend Framework 3 - Middleware-Anwendungen bauen&quot;
    auf der IPC2017 Spring Edition lernen Sie, wie Sie Middleware-Anwendungen
    mit Zend\Expressive erstellen können.
  </p>
  <p>
    <a href="/db-check.php" class="btn btn-primary">Datenbank Test</a>
  </p>
</div>
