<?php
/**
 * IPC2017 Zend\Expressive Workshop
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/RalfEggert/ipc2017-expressive
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
$customer = $this->customer;
?>
<h1>Kunde anzeigen</h1>
<table class="table">
    <tbody>
    <tr>
        <th>ID</th>
        <td><?= $customer['id'] ?></td>
    </tr>
    <tr>
        <th>Vorname</th>
        <td><?= $customer['first_name'] ?></td>
    </tr>
    <tr>
        <th>Nachname</th>
        <td><?= $customer['last_name'] ?></td>
    </tr>
    <tr>
        <th>E-Mail</th>
        <td><?= $customer['email'] ?></td>
    </tr>
    </tbody>
</table>
<hr>
<a href="<?= $this->url('customer'); ?>" class="btn-primary btn">Kundenliste</a>
