<?php
/**
 * IPC2017 Zend\Expressive Workshop
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/RalfEggert/ipc2017-expressive
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$createUrl = $this->url('customer-create-form');
?>
<h1>Kundenliste</h1>
<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Vorname</th>
    <th>Nachname</th>
    <th>Land</th>
    <th>E-Mail</th>
    <th>Status</th>
    <th>Datum</th>
    <th><a href="<?= $createUrl ?>" class="btn btn-primary">Anlegen</a></th>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($this->customerList as $customer) : ?>
      <?php
      $showUrl   = $this->url('customer-show', ['id' => $customer['id']]);
      $updateUrl = $this->url(
          'customer-update-form', ['id' => $customer['id']]
      );
      ?>
    <tr>
      <td><?= $customer['id'] ?></td>
      <td><?= $customer['first_name'] ?></td>
      <td><?= $customer['last_name'] ?></td>
      <td><?= $customer['country'] ?></td>
      <td><?= $customer['email'] ?></td>
      <td><?= $customer['status'] ?></td>
      <td><?= $customer['date'] ?></td>
      <td>
        <a href="<?= $showUrl ?>" class="btn btn-primary">Anzeigen</a>
        <a href="<?= $updateUrl ?>" class="btn btn-primary">Bearbeiten</a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
