<?php
/**
 * IPC2017 Zend\Expressive Workshop
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/RalfEggert/ipc2017-expressive
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use CustomerApp\Form\CustomerForm;

/** @var CustomerForm $customerForm */
$customerForm = $this->customerForm;
$customerForm->setAttribute('action', $this->url('customer-update-form', ['id' => $this->customer['id']]));

?>
<h1>Kunde bearbeiten</h1>
<?= $this->bootstrapForm($customerForm); ?>
<hr>
<p>
  <a href="<?= $this->url('customer-list') ?> " class="btn btn-primary">
    Kundenliste
  </a>
</p>
